import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';

class Utils{

  static void toastMessage(String message) {
    Fluttertoast.showToast(
      msg: message,
      backgroundColor: Colors.black,
      textColor: Colors.white,
    );
  }

 static List<String> cities = [
   "Karachi",
   "Lahore",
   "Faisalabad",
   "Rawalpindi",
   "Gujranwala",
   "Peshawar",
   "Multan",
   "Hyderabad",
   "Islamabad",
   "Quetta",
   "Bahawalpur",
   "Sargodha",
   "Sialkot",
   "Sukkur",
   "Larkana",
   "Rahim Yar Khan",
   "Sheikhupura",
   "Jhang",
   "Dera Ghazi Khan",
   "Gujrat",
   "Sahiwal",
   "Wah Cantonment",
   "Mardan",
   "Kasur",
   "Okara",
   "Mingora",
   "Nawabshah",
   "Chiniot",
   "Kotri",
   "Kāmoke",
   "Hafizabad",
   "Sadiqabad",
   "Mirpur Khas",
   "Burewala",
   "Kohat",
   "Khanewal",
   "Dera Ismail Khan",
   "Turbat",
   "Muzaffargarh",
   "Abbottabad",
   "Mandi Bahauddin",
   "Shikarpur",
   "Jacobabad",
   "Jhelum",
   "Khanpur",
   "Khairpur",
   "Khuzdar",
   "Pakpattan",
   "Hub",
   "Daska",
   "Gojra",
   "Dadu",
   "Muridke",
   "Bahawalnagar",
   "Samundri",
   "Tando Allahyar",
   "Tando Adam",
   "Jaranwala",
   "Chishtian",
   "Muzaffarabad",
   "Attock",
   "Vehari",
   "Kot Abdul Malik",
   "Ferozwala",
   "Chakwal",
   "Gujranwala Cantonment",
   "Kamalia",
   "Umerkot",
   "Ahmedpur East",
   "Kot Addu",
   "Wazirabad",
   "Mansehra",
   "Layyah",
   "Mirpur",
   "Swabi",
   "Chaman",
   "Taxila",
   "Nowshera",
   "Khushab",
   "Shahdadkot",
   "Mianwali",
   "Kabal",
   "Lodhran",
   "Hasilpur",
   "Charsadda",
   "Bhakkar",
   "Badin",
   "Arif Wala",
   "Ghotki",
   "Sambrial",
   "Jatoi",
   "Haroonabad",
   "Daharki",
   "Narowal",
   "Tando Muhammad Khan",
   "Kamber Ali Khan",
   "Mirpur Mathelo",
   "Kandhkot",
   "Bhalwal",
 ];

}